# Programming Assignment 2 - Divisible by 3 problem

In [2]:
# create a 10 x 10 array which are the squares of the first 100 positive integers.
# From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

### [START OF CODE]

In [3]:
# Import numpy 
import numpy as np

# Create the 10 x 10 array
array = np.arange(1,101,1).reshape(10,10) ** 2

# Display the table
print("The 10 x 10 table consisting of the squares of the first 100 positive integers: \n") 
print(array)

#output variable
div_by_3 = []

# if statement (divisible by 3)
for i in range(array.shape[0]): #rows
    for j in range(array.shape[1]): #columns
        if array[i, j] % 3 == 0:
            div_by_3.append(array[i,j])
            
# output in a straight line
print(" \n The following elements are divisible by 3: \n")
print(' '.join(map(str, div_by_3)))

The 10 x 10 table consisting of the squares of the first 100 positive integers: 

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
 
 The following elements are divisible by 3: 

9 36 81 144 225 324 441 576 729 900 1089 1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801


### [END OF CODE]