# Programming Assignment 2 - Normalization problem

In [ ]:
# Normalization is one of the most basic preprocessing techniques in
# data analytics. This involves centering and scaling process. Centering means subtracting the data from the
# mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
# expressed as: z = (X - x bar)/standard deviation

# In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
# .std() calls.
# In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
# ndarray as X_normalized.npy

### [START OF CODE]

In [16]:
# Import numpy in the code
import numpy as np

# Random 5x5 array - change to integers using .randint
X = np.random.randint(0,999, size = (5,5))

#Display the array
print("The randomly generated array is: ")
print("")
print(X)

#Get the mean of X using .mean()
print("")
mean = X.mean()
print(f"The mean of the array is: {mean}")

#Centering X - x bar
centering = X - mean
print("")
print("Centered values are: ")
print("")
print(centering)

#Standard deviation
sd = round(centering.std(),4)

print("")
print(f"The standard deviation of the array is: {sd}")

#Normalization
X_normalized = centering/sd

#Output
print("")
print(f"The normalized value of the array is: \n\n {X_normalized} ")

The randomly generated array is: 

[[276 719 381 872 210]
 [791 623 732 243 477]
 [346 132 714 195 492]
 [518 664 519  47 169]
 [115 958 590 457 206]]

The mean of the array is: 457.84

Centered values are: 

[[-181.84  261.16  -76.84  414.16 -247.84]
 [ 333.16  165.16  274.16 -214.84   19.16]
 [-111.84 -325.84  256.16 -262.84   34.16]
 [  60.16  206.16   61.16 -410.84 -288.84]
 [-342.84  500.16  132.16   -0.84 -251.84]]

The standard deviation of the array is: 253.4014

The normalized value of the array is: 

 [[-0.71759667  1.03061783 -0.30323432  1.63440297 -0.978053  ]
 [ 1.31475201  0.65177225  1.08191983 -0.84782483  0.07561126]
 [-0.4413551  -1.28586503  1.01088629 -1.03724762  0.13480589]
 [ 0.2374099   0.81357088  0.2413562  -1.62130122 -1.13985163]
 [-1.35295227  1.97378546  0.52154408 -0.0033149  -0.99383823]] 


### [END OF CODE