# Programming Assignment 2 - Normalization problem

In [ ]:
# Normalization is one of the most basic preprocessing techniques in
# data analytics. This involves centering and scaling process. Centering means subtracting the data from the
# mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
# expressed as: z = (X - x bar)/standard deviation

# In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
# .std() calls.
# In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
# ndarray as X_normalized.npy

### [START OF CODE]

In [5]:
# Import numpy in the code
import numpy as np

# Random 5x5 array - change to integers using .randint
X = np.random.randint(0,999, size = (5,5))

#Display the array
print("The randomly generated array is: ")
print("")
print(X)

#Get the mean of X using .mean()
print("")
mean = X.mean()
print(f"The mean of the array is: {mean}")

#Centering X - x bar
centering = X - mean
print("")
print("Centered values are: ")
print("")
print(centering)

#Normalization
X_normalized = round(centering.std(),2)

print("")
print(f"The normalized value of the array is: {X_normalized}")

The randomly generated array is: 

[[607 722 412 893 353]
 [863 789  55 830 107]
 [252 791 108 167 183]
 [119 561 271 498 692]
 [421 512 981  57 720]]

The mean of the array is: 478.56

Centered values are: 

[[ 128.44  243.44  -66.56  414.44 -125.56]
 [ 384.44  310.44 -423.56  351.44 -371.56]
 [-226.56  312.44 -370.56 -311.56 -295.56]
 [-359.56   82.44 -207.56   19.44  213.44]
 [ -57.56   33.44  502.44 -421.56  241.44]]

The normalized value of the array is: 292.68


### [END OF CODE