# Programming Assignment 2 - Normalization problem and Div_by_3 Problem

# [NORMALIZATION PROBLEM]

In [ ]:
# Normalization is one of the most basic preprocessing techniques in
# data analytics. This involves centering and scaling process. Centering means subtracting the data from the
# mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
# expressed as: z = (X - x bar)/standard deviation

# In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
# .std() calls.
# In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
# ndarray as X_normalized.npy

### [START OF CODE]

In [37]:
# Import numpy in the code
import numpy as np

# Random 5x5 array - change to integers using .randint
X = np.random.randint(0,999, size = (5,5))

#Display the array
print("The randomly generated array is: ")
print("")
print(X)

#Get the mean of X using .mean()
print("")
mean = X.mean()
print(f"The mean of the array is: {mean}")

#Centering X - x bar
centering = X - mean

#Standard deviation
sd = round(centering.std(),4)

print("")
print(f"The standard deviation of the array is: {sd}")

#Normalization
X_normalized = centering/sd

print("\n The normalized array is:")

#Save your ndarray and give it a name
np.save('X_normalized.npy', X_normalized)

#Load your ndarray
np.load('X_normalized.npy')

The randomly generated array is: 

[[218 184  62  64 321]
 [159 765 155 144 463]
 [710 934 688 790 686]
 [668  89 574 147 948]
 [773 291 507 758 602]]

The mean of the array is: 468.0

The standard deviation of the array is: 290.5893

 The normalized array is:


array([[-0.86032073, -0.97732435, -1.39716087, -1.39027831, -0.50586859],
       [-1.06335643,  1.02206103, -1.07712156, -1.11497567, -0.01720641],
       [ 0.83279047,  1.60363785,  0.75708225,  1.10809311,  0.75019968],
       [ 0.68825659, -1.30424623,  0.36477599, -1.10465182,  1.65181581],
       [ 1.0495913 , -0.60910708,  0.13421003,  0.99797205,  0.46113191]])

### [END OF CODE

# [Div_by_3 Problem]

### [START OF CODE]

In [ ]:
# create a 10 x 10 array which are the squares of the first 100 positive integers.
# From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [35]:
# Import numpy 
import numpy as np

# Create the 10 x 10 array
array = np.arange(1,101,1).reshape(10,10) ** 2

# Display the table
print("The 10 x 10 table consisting of the squares of the first 100 positive integers: \n") 
print(array)

#output variable
div_by_3 = []

# if statement (divisible by 3)
for i in range(array.shape[0]): #rows
    for j in range(array.shape[1]): #columns
        if array[i, j] % 3 == 0:
            div_by_3.append(array[i,j])

# Save the result as a .npy file
np.save('div_by_3.npy', div_by_3 )


# output in a straight line
print(" \n The following elements are divisible by 3: \n")

#Format the output and load the result
print(' '.join(map(str, np.load('div_by_3.npy'))))

The 10 x 10 table consisting of the squares of the first 100 positive integers: 

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
 
 The following elements are divisible by 3: 

9 36 81 144 225 324 441 576 729 900 1089 1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801


### [END OF CODE]